services:
  mysql:
    image: mysql:8.0
    container_name: nova-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: nova_member
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 87654321
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
